# -*- coding: utf-8 -*-
"""Project_Titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/thecodescholar/DA_Python_Jun_21/blob/main/Project_Titanic.ipynb

# Project_titanic
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# %matplotlib inline

"""## Data Operations Task

#### Q. Import the Titianic Dataset and Display the Head of the Dataset
"""

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/thecodescholar/DA_Python_Jun_21/main/Dataset/titanicDataset.csv')
df.head()

"""#### Q. Show the Statistics of dataframe"""

df.describe()

"""#### Q. Display last 3 columns"""

df.iloc[0:5,4:]

"""#### Q. Show Unique values in Embarked"""

df.Embarked.unique()

"""## Visualization Task

#### Q. Draw histogram for Age, using Matplotlib
"""

plt.hist(df.Age)

"""#### Q. Draw countplot for Sex, using Seaborn"""

sb.countplot(x='Sex',data = df)
plt.show

"""#### Q. Make a Pie Chart of Corona Cases by taking numbers list as [500000, 1800000, 1200000] and labels list as ["Deaths", "Total Cases", "Cured"]"""

y = np.array([500000,1800000,1200000])
lables= ["death", "total cases", "cured"]
plt.pie(y,labels =lables)
plt.show()

"""### Great Job

## All the Best

# THE CODE SCHOLAR
"""